buildpacks = [
  { id = "paketo-buildpack/dotnet-core", image = "gcr.io/paketo-buildpacks/dotnet-core:0.0.5" },
  { id = "paketo-buildpack/java",        image = "gcr.io/paketo-buildpacks/java:1.14.0" },
  { id = "paketo-buildpack/php",         image = "gcr.io/paketo-buildpacks/php:0.0.7" },
  { id = "paketo-buildpacks/go",         image = "gcr.io/paketo-buildpacks/go:0.0.8" },
  { id = "paketo-buildpacks/nodejs",     image = "gcr.io/paketo-buildpacks/nodejs:0.0.3" },
]
[[order]]
group = [
  { id = "paketo-buildpacks/go",version = "0.0.8" },
]
[[order]]
group = [
  { id = "paketo-buildpacks/nodejs",version = "0.0.3" },
]
[[order]]
group = [
  { id = "paketo-buildpacks/java",version = "1.14.0" },
]
[[order]]
group = [
  { id = "paketo-buildpacks/dotnet-core",version = "0.0.5" },
]
[[order]]
group = [
  { id = "paketo-buildpacks/php",version = "0.0.7" },
]
[lifecycle]
version = "0.8.0"
[stack]
id          = "org.cloudfoundry.stacks.cflinuxfs3"
build-image = "cnbs/ubi-sample-stack-build:ubi-redhat"
run-image   = "cnbs/ubi-sample-stack-run:ubi-redhat"
